### ISSUE TITLE
Functions beginning with an underscore are fontified as comments

### ISSUE THREAD

**Issue by John-Goff** [wkirschbaum/elixir-ts-mode#40]
In my codebase, it's convention to define private functions starting with an underscore so it's easily distinguishable at a glance if a function is private or imported/public when reading a block of code. However, they are being fontified with `font-lock-comment-face`, which I believe to be due to fontifying ignored pattern matches that way. While that behaviour is desirable for variables I'd still like my functions to be fontified as functions, regardless of their naming scheme. 

Steps to reproduce:
```elixir
defmodule FontifiedFunctions do
  def my_public_function() do
    _my_private_function() # <-- will be fontified as a comment
  end

  defp _my_private_function() do # <-- will also be fontified as a comment
    IO.puts("Hello world!")
  end
end
```

**Comment by wkirschbaum** [comment]
I can confirm this is a bug, will have a look at it at some point.

**Comment by wkirschbaum** [comment]
Fixed by https://github.com/wkirschbaum/elixir-ts-mode/commit/70254355700ea5fa7fdfb5da42908f7b19cddb25

**Comment by John-Goff** [comment]
Unfortunately this is not 100% resolved, the function definition is fixed but the callsite is still showing as a comment. 

```elixir
defmodule FontifiedFunctions do
  def my_public_function() do
    _my_private_function() # <-- still fontified as a comment
  end

  defp _my_private_function() do # <-- No longer fontified as a comment
    IO.puts("Hello world!")
  end
end
```

**Comment by John-Goff** [comment]
Hi @wkirschbaum sorry for the tag, just wanted to confirm that you're aware this is still not perfectly resolved. Function definitions were fixed, however function calls were not.

**Comment by wkirschbaum** [comment]
@John-Goff o, i was not aware, thanks for pining. I will look into it.

**Comment by wkirschbaum** [comment]
I have a potential fix, but need to do some testing to see if it does not break other parts.

**Comment by wkirschbaum** [comment]
@John-Goff mind trying again on the latest MELPA build? From my limited tested it looks to work now, but might be missing a case or two.

**Comment by John-Goff** [comment]
Seems to be working! Thanks for the fix :)
