### ISSUE TITLE
Weirdness with treesit font lock configuration

### ISSUE THREAD

**Issue by 1player** [wkirschbaum/elixir-ts-mode#41]
I'm trying to tweak the font lock because I find by default this mode is highlighting every single word compared to elixir-mode, and it's too much for my eyes. I'd rather prefer normal identifier to be black, and color to be a sprinkle on top, not the main course :)

For that reason I'm using the `treesit-font-lock-recompute-features` function to disable highlighting of a few things and it does not work as expected. This is an example incantation that should disable highlighting of comments and strings:

```
  (defun fix-elixir-ts-font-lock ()
    (treesit-font-lock-recompute-features '() '(elixir-string elixir-comment)))
 (add-hook 'elixir-ts-mode-hook #'fix-elixir-ts-font-lock)
```

Yet strings and comments now instead of being unhighlighted (black) get another color. This is because they are also considered `heex-attribute` for some reason, which seems to be a catch-all rule that matches basically every single token in the document. If I also disable "heex-attribute" highlighting, everything works as expected. Like so:

```
(treesit-font-lock-recompute-features '() '(elixir-string elixir-comment heex-attribute))
```

It makes no sense that everything in an Elixir file is also marked as heex-attribute, so I believe there's a hidden bug either in the grammar or this mode, which would cause weird issues like this one. Also, I am testing with a LiveView module, so HEEX highlighting is enabled together with Elixir highlighting. You might not be able to reproduce on a plain Elixir file.

**Comment by 1player** [comment]
This might be the reason of all the other highlighting issues that are currently open.

Other weird ones: 

- disabling `elixir-call` (to disable highlighting of function calls), also affects stuff like if, def, alias, etc. Other keywords like "else" or "end" are not. Technically if, def, alias etc. are all function calls, but they should be categorized as keywords instead.
- Types/module names are tagged as `elixir-operator`
- Regular variables and function parameters are `elixir-constant`. Other languages usually have an "identifier" type, and constants would be used for numbers or well known atoms like true, false, nil, etc.

**Comment by wkirschbaum** [comment]
@1player Have you tried using `treesit-font-lock-level'? Maybe set it to level 1 or 2 and let me know if you have any feedback on tweaking this. What you are describing sounds like weird behaviour and don't think it is how it's suppose to work. Which version of emacs are you using? 

I can look into it, but might take a bit longer as its not a use-case I have seen before.

**Comment by wkirschbaum** [comment]
Okay, I see there is a bit of overriding if even the level is set. I am busy doing slight tweaks to the levels atm and will be out in a couple of days hopefully.  I will highly recommend rather using `treesit-font-lock-level' over overriding the features and report if something does not look right.

**Comment by 1player** [comment]
I've set treesit-font-lock-level already to 2 down from 3, but the reason I'm tweaking manually is because the result is still too much, and set to 1 disables highlight to stuff like strings, which are perhaps with comments the only two things that I want to see highlighted.

The issue is not the font lock level, is that words seem to be tagged incorrectly as I explained above.

**Comment by wkirschbaum** [comment]
@1player I just pushed up some changes which might solve some of your issues. It does more specific matching on identifiers.  I tested with all 4 levels and seems to solve some of the obvious issues I have seen.

**Comment by 1player** [comment]
Thanks. I've updated but I still see heex rules affecting regular Elixir files.

What I'm using this days not to have a complete rainbow of colors is `(treesit-font-lock-recompute-features '() '(elixir-constant heex-attribute))`. This is what it looks after tweaking:

![Screenshot_20231218_164436](https://github.com/wkirschbaum/elixir-ts-mode/assets/690120/48613ad4-a20c-4134-b023-1b357fb53fce)

This is what it looks by default:

![Screenshot_20231218_164412](https://github.com/wkirschbaum/elixir-ts-mode/assets/690120/d2e814c4-a63b-45dd-8220-4d2b660b2f13)

I don't see why every single word has to be highlighted. I feel it should be a sprinkle on top, not everything blue. Someone also wrote a post about this issue (https://andreyor.st/posts/2023-11-17-overcolorization/). I don't want to sound overly critical, I just feel most people like the rainbow approach, while I'd rather have colour to help me understand, not to overwhelm me :-)
